### ISSUE TITLE
Discrepancy between serial and parallel output

### ISSUE THREAD

**Issue by ppapasaikas** [ppapasaikas/griph#1] opened 2017-04-06 07:59 UTC
There is discrepancy in the output returned from the serial and the parallel implementations.
At this point this looks more like a precision error...

**Comment by mbstadler** [comment] 2017-04-25 12:06
The following code compares serial and parallel output for one of the test datasets:
```
library(griph)
M <- readRDS(system.file("extdata", "buettner_top10k.rds", package = "griph"))
label <- attr(M, "label")
res <- SC_cluster(M, ClassAssignment = label)
resP <- SC_cluster(M, ClassAssignment = label, use.par = TRUE, ncores = 8)
for(nm in names(res))
    cat(nm,":",identical(res[[nm]], resP[[nm]]), "\n")
```
Indeed, the components `DISTM`, `GRAO` and `plotGRAO` are not identical.
However:
```
all.equal(res$DISTM, resP$DISTM)
isomorphic(res$GRAO, resP$GRAO)
isomorphic(res$plotGRAO, resP$plotGRAO)
```
`DISTM` is identical allowing for small deviations due to machine precision, and the graphs are isomorphic, indicating that also here the non-identity might be caused by numerical imprecision (e.g. on the edge weights).

I will add a unit test that formally checks identity of results (within machine precision) and close this issue.

**Closed by mbstadler** 2017-04-25 12:06 UTC
